# Generated by Django 4.2.3 on 2023-08-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reagency", "0004_scoutedproperty_reason_for_rejection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="scouted_property",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="reagency.scoutedproperty",
            ),
        ),
    ]
