# Generated by Django 4.2.3 on 2023-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagency", "0005_property_scouted_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutedproperty",
            name="in_estate",
            field=models.CharField(default="", max_length=3),
        ),
    ]
