# Generated by Django 4.2.3 on 2023-08-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagency", "0006_scoutedproperty_in_estate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoutedproperty",
            name="location",
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="area_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="estate_name",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="lga",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="manager_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="manager_tel",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="owner_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="owner_tel",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="state",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="scoutedproperty",
            name="street",
            field=models.CharField(default="", max_length=50),
        ),
    ]
