# Generated by Django 4.2.3 on 2023-09-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reagency", "0007_remove_scoutedproperty_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlorduser",
            name="emergency_contact_address",
        ),
        migrations.RemoveField(
            model_name="landlorduser",
            name="emergency_contact_email",
        ),
        migrations.RemoveField(
            model_name="landlorduser",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="landlorduser",
            name="emergency_contact_phone",
        ),
    ]
