# Generated by Django 4.2.3 on 2023-09-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagency", "0008_remove_landlorduser_emergency_contact_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="scout",
        ),
        migrations.AddField(
            model_name="property",
            name="in_estate",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="property",
            name="rent_sale",
            field=models.CharField(max_length=10),
        ),
    ]
