# Generated by Django 4.2.3 on 2023-09-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reagency", "0009_remove_property_scout_property_in_estate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="landlord",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propowner",
                to="reagency.landlorduser",
            ),
        ),
    ]
